version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  onfit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onfit-backend
    command: npm run dev   # nodemon 실행
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app             # 호스트 → 컨테이너 소스 코드 동기화
      - /app/node_modules   # 컨테이너 전용 node_modules 유지 (호스트 오염 방지)
