version: "3.9"

volumes:
  redis-data:
  hf_cache:

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - redis-data:/data

  onfit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onfit-backend
    restart: always
    depends_on:
      - redis
      - rmbg-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      HF_HOME: /app/.venv/huggingface
      HF_RMBG_MODEL_PATH: /app/.venv/huggingface/models--briaai--RMBG-1.4
      HF_INPAINT_MODEL_PATH: /app/.venv/huggingface/stable-diffusion-inpainting
    volumes:
      - hf_cache:/app/.venv/huggingface

  rmbg-api:
    build:
      context: ./src/modules/item
      dockerfile: Dockerfile.python
    container_name: rmbg-api
    environment:
      HF_HOME: /app/.venv/huggingface
      HF_RMBG_MODEL_PATH: /app/.venv/huggingface/models--briaai--RMBG-1.4
      HF_INPAINT_MODEL_PATH: /app/.venv/huggingface/stable-diffusion-inpainting
    volumes:
      - hf_cache:/app/.venv/huggingface
