services:
  nodejs:
    image: munwalk/onfit-nodejs:latest  # DockerHub에서 자동 pull
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env.production  # 환경 변수는 여기에

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: onfit
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: jang1823!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  rmbg-api:
    build:
      context: ./src/modules/item/rmbg_api
    ports:
      - "7860:7860"

volumes:
  mysql-data:
