version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  onfit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onfit-backend
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # node_modules 절대 마운트 금지
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro