version: "3.8"

services:
  backend:
    build: .
    container_name: onfit-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: onfit-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
